version: '3.8'

services:
  # Backend API (usando MongoDB Atlas)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: chat-backend
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      PORT: 5000
      # MongoDB Atlas connection string
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET:-your-super-secret-jwt-key}
      JWT_EXPIRE: 7d
      CLIENT_URL: ${CLIENT_URL:-https://suporte.brsi.net.br}
      # AWS S3 Configuration
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET_NAME: ${S3_BUCKET_NAME}
      AWS_REGION: ${AWS_REGION:-us-east-1}
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - chat-network

  # Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL:-https://suporte.brsi.net.br/api}
        VITE_SOCKET_URL: ${VITE_SOCKET_URL:-https://suporte.brsi.net.br}
    container_name: chat-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge
